### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by kraujinis**
Start new job

### CODE REVIEW

**Comment by kraujinis** [comment]
**db structure?**
-id
-task_name
-task_description
-task_status

**Comment by vladas333** [comment]
does we need a time limit until to do?

**Comment by kraujinis** [comment]
> does we need a time limit until to do?

no, I think, but until the end of the lesson we must show something to Mindaugas :)

**Review by vladas333 — APPROVED** [review]
The beginning of your work is good, I will adjust it a bit and upload it today.

**Comment by kraujinis** [comment]
closed

**Comment by kraujinis** [comment]
closed because the code didn't prepare for the main repository

**Pull request closed without merging**
